services:
  postgres:
    image: postgres:15
    container_name: pql-taskmind-container
    restart: always
    environment:
      POSTGRES_DB: pql-taskmind-db
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    ports:
      - '5432:5432'
    volumes:
      - pg-taskmind-v:/var/lib/postgresql/data

volumes:
  pg-taskmind-v: 
